# Generated by Django 4.2.11 on 2024-05-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperuser',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paperuser',
            name='background_url',
            field=models.CharField(default='https://pic.netbian.com/uploads/allimg/240320/231320-17109476001a93.jpg', max_length=100),
        ),
    ]
